apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-final-project
  labels:
    app: devops-final-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-final-project
  template:
    metadata:
      labels:
        app: devops-final-project
    spec:
      containers:
        - name: devops-final-project-container
          image: srijeshk/devops-final-project-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: devops-final-project-config
                  key: REACT_APP_API_URL
            - name: REACT_APP_FEATURE_FLAG
              valueFrom:
                configMapKeyRef:
                  name: devops-final-project-config
                  key: REACT_APP_FEATURE_FLAG
            - name: REACT_APP_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: devops-final-project-config
                  key: REACT_APP_ENVIRONMENT
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
