pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                git 'https://github.com/regmimilan/devops-final-project.git'
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'npm run deploy'
            }
        }
    }
}

