name: Node.js CI/CD

on:
  push:
    branches: ["devops-project"]
  pull_request:
    branches: ["devops-project"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: |
          docker build -t srijeshk/devops-final-project-frontend:latest .
        env:
          DOCKER_BUILDKIT: 1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: srijeshk
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push srijeshk/devops-final-project-frontend:latest

      - name: Set up Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube /usr/local/bin/
          mkdir -p $HOME/.kube $HOME/.minikube
          sudo chown -R $USER $HOME/.kube $HOME/.minikube
          kubectl config view --merge --flatten > $HOME/.kube/config

      - name: Set up KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Test Kubernetes API Connectivity
        run: kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          minikube start
          minikube status
          kubectl apply -f k8s/configmap.yaml --validate=false
          kubectl apply -f k8s/deployment.yaml --validate=false
          kubectl apply -f k8s/service.yaml --validate=false
          kubectl get all
